language: objective-c
osx_image: xcode9.4
before_install:
    - brew tap vapor/homebrew-tap
    - brew upgrade
    - brew install vapor    
    - swift package resolve
    - swift package generate-xcodeproj
script:
    - swift test
after_success:
  - bash <(curl -s https://codecov.io/bash)
